blockchain/beaconbridgeproducer.go, blockchain/beaconprocess.go, blockchain/beaconproducer.go, blockchain/burn_test.go, blockchain/error.go, blockchain/shardprocess.go, mocks/DatabaseInterface.go
- Pass new beacon block height to GetShardStateFromBlock
- buildBridgeInstruction builds BurningConfirm with new beacon block
height (no increasing by one)
- Re-enable StoreCommitteeFromShardBestState
- Log instructions of beacon producer and validators
=> Fix bug build beacon instructions with different block height

bin/centralized-logging/elk/docker-compose.yml, bin/centralized-logging/elk/docker-stack.yml, bin/centralized-logging/elk/elasticsearch/Dockerfile, bin/centralized-logging/elk/kibana/Dockerfile, bin/centralized-logging/elk/logstash/Dockerfile, bin/centralized-logging/elk/logstash/pipeline/logstash.conf, bin/centralized-logging/filebeat/Dockerfile, bin/centralized-logging/filebeat/filebeat.yml
This PR is to add configuration for a centralized logging system that is being set up with ELKB stack:
- ELK is being set up on the logging server.
- Filebeat is being set up on every single incognito node.
Currently the setup has yet supported 2 logging formats: plain text & JSON. The sample result might be shown at:
http://34.94.185.164:5601/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2Fd,to:now%2Fd))&_a=(columns:!(log.file.path,event,session_id,user,verified,id,ductestfield),index:c3c81180-f213-11e9-98cd-4b3eff72c77d,interval:auto,query:(language:kuery,query:'log.file.path:%20*json*'),sort:!('@timestamp',desc))
=> Add configuration for centralized logging system

specs/validator_random_substitution.md
github markdown doesn't display mathjax.  removed all mathjax syntax and just use regular text.
=> fixing math display problem

blockchain/bridge_test.go, blockchain/shardproducer.go, go.mod, go.sum, mocks/DatabaseInterface.go
Fix bug ETH bridge's SwapConfirm instruction doesn't contain block producer.
Also, add unittest to make sure it won't happen again.
=> Fix eth bridge missing producer

blockchain/beaconpdeprocess_test.go, blockchain/pdeflows_test.go
The PR is to create a simulated DEX flow test so that we can test multiple trades, add/remove liquidity instructions in the same beacon block.
=> Simulate PDEX flows

blockchain/beaconpdeprocess.go, blockchain/beaconpdeproducer.go, blockchain/pdetxsbuilder.go, database/lvdb/pde.go, metadata/pdecontribution.go
The PR is to add tx request id to contribution refund tx in order to avoid txs duplication issues.
=> Add tx request id to contribution refund tx

metadata/pdewithdrawalrequest.go
The PR is to fix the sanity validation issue for pdex withdrawal request as withdrawal request tx type is always normal privacy.
=> Fix the sanity validation issue for pdex withdrawal request

blockchain/pdetxsbuilder.go, metadata/pdewithdrawalresponse.go
The PR is to add tokenid string to pde withdrawal response metadata in order to avoid duplicated txs.
=> Deduplicate removing liquidity txs

blockchain/synker.go
- Not sync from pool in GetCrossShard case, cuz HW will redirect this
request to node who already has blocks in db.
=> Hot fix synker

blockchain/retrieverformetadata.go, metadata/issuingrequest.go, metadata/metadata.go
Should get beacon height of current shard state, instead of beacon state.
=> Validate tx with correct  beacon height

metadata/issuingethrequest.go, metadata/issuingrequest.go
The PR is about to fix a race condition issue between trusted and trustless bridge on shields with the same token id (yes, allowing a client to input token id to shield metadata was a design debt). The issue might cause an inconsistency between block creation and block syncing processes. For example, a transaction for requesting an issuance on a trusted bridge might bypass validation at a shard but get rejected at beacon due to another shield with trustless bridge for the same token id. Unfortunately, when a node syncs the transaction, it would not bypass the “ValidateTxWithBlockChain” validation. That’s why we need to remove the unnecessary validation rules as it is verified strictly at beacon.
=> Remove unnecessary validation rules for shield processes

blockchain/beaconbeststate.go, blockchain/beaconpdeprocess.go, blockchain/beaconprocess.go, blockchain/beaconstatefulinsts.go, blockchain/pdeutils.go, blockchain/shardprocess.go, dataaccessobject/statedb/accessor_pde.go, rpcserver/http_pde.go
- Store only change keypair
- Instead of initiating pdex from DB, store the current state in beacon view, and then reuse it (still keep the legacy logic of using beaconheight in key prefix)
=> Optimize pdex init & insert

metadata/common/accumulatedvalues.go, metadata/common/constants.go, metadata/common/error.go, metadata/common/log.go, metadata/common/metadata.go, metadata/common/metadatabase.go, metadata/common/utils.go, metadata/exports.go, metadata/parse.go
- keep as much current code as possible
- code that will be reused go in `common`
- re-export necessary symbols in `exports.go`
- allow new pdex-v3 metadata types to go in its own subfolder
=> move shared code to common

dataaccessobject/statedb/constants.go
Avoid mistakes when creating new state objects that can corrupt the StateDB
=> Change object types from iota enum to hard code values

metadata/common/constants.go, metadata/common/utils.go, metadata/exports.go, metadata/parse.go, metadata/pdexv3/addOrder.go, metadata/pdexv3/trade.go, privacy/coin/receiver.go, privacy/coin/receiver_test.go, privacy/privacy_exports.go, wallet/constants.go
- define new metadata types + constants for trade & addOrder flow
- define OTAReceiver struct as `privacy` substitute for PaymentAddress when sending coin
- move `calculateSize` to `metadata/common`
- future work : withdrawOrder metadata; validation functions
=> OTA Receiver struct + Metadata for trades

blockchain/shardbeststate.go
Testnet 2: block created by staking flow v2 should have version 3, but somehow some block got version 2 only
=> [hotfix] get committee with block version

blockchain/beaconbeststate.go
- Incase, we clone pdex state to empty beacon view (call from rpc)
=> Init pdestate if not init

blockchain/beaconbeststate.go, blockchain/blockchain.go, blockchain/pdex/interface.go, blockchain/pdex/state_base.go, blockchain/pdex/state_processor_v2.go, blockchain/pdex/state_processor_v2_test.go, blockchain/pdex/state_producer_v2.go, blockchain/pdex/state_producer_v2_test.go, blockchain/pdex/state_v1.go, blockchain/pdex/state_v2.go, blockchain/pdex/statedb.go, blockchain/pdex/v2utils/utils.go, privacy/coin/coin_v2.go, privacy/coin/coin_v2_ca.go, privacy/privacy_exports.go, privacy/privacy_v2/common.go, rpcserver/rpcservice/pdexv3service.go, rpcserver/rpcservice/txservice.go, transaction/tx_generic/common.go, transaction/tx_generic/tx_base.go, transaction/tx_generic/tx_token_base.go, transaction/tx_ver2/common.go, transaction/tx_ver2/tx_token_ver2.go, transaction/tx_ver2/tx_ver2.go, transaction/tx_ver2/tx_ver2_ca.go, transaction/tx_ver2/tx_ver2_ca_newpool.go, transaction/tx_ver2/tx_ver2_newpool.go
In this PR:
- update TX ring signing in fullnode
- no longer pick NFTID coins
- handling for non-private tokens / burn-only tokens
- they cannot be added to standard ring
- burn-only input tokens have their receiver verified (must be burning address)
- update "randomcommitmentandpublickeys" RPC method
- upon reading unwanted random coin, retry with `max_attempts` instead of indefinitely
=> [pdex-v3] implement burn-only tokens; update coin picker for ringSig

dataaccessobject/statedb/statedb.go
Committee list need to be sort by enter_time to maintain its index before process salary instruction
=> [hotfix] Sort committee before process salary instruction

blockchain/pdex/statedb.go, rpcserver/rpcservice/constants.go, rpcserver/rpcservice/pdexv3service.go
Current verbosity levels do not help traders effectively. Either she has to get full state object or aggregate the required state by calling multiple RPCs. PR removes this dilemma.
=> Liquidity verbosity for pdexv3State/PoolPairs RPC
