incognitochain/incognito-chain

- common/constants.go
@0xsirrush please help review, thanks.
> Update centralized website's pk

- blockchain/reserve.go
please help review, a @0xsirrush, thanks.
> Fix reserve issuance

- blockchain/constants.go
- database/lvdb/epochreward.go
- metadata/withdrawreward.go
- rpcserver/rpcwithdrawreward.go
Please review and merge this. Fix a little bug.
> Master new blockreward

- rpcserver/constants.go
- rpcserver/rpcfunction.go
- rpcserver/rpcwithdrawreward.go
@0xkaguya  Add helpful RPC function. Please merge this.
> Add RPC reward getting function

- database/lvdb/epochreward_test.go
- database/lvdb/keyepochreward_test.go
Add happy test case for epoch reward database
> Add happy test case

- mempool/mempool.go
- server.go
Temppool not start => not receive pubsub event => hang channel event
> fix leak mem

- blockchain/beaconprocess.go
- blockchain/shardprocess.go
- blockchain/shardproducer.go
- connmanager/connmanager.go
- consensus/signatureschemes/blsmultisig/bls.go
- consensus/signatureschemes/blsmultisig/constant.go
- consensus/signatureschemes/blsmultisig/ec.go
- consensus/signatureschemes/blsmultisig/ec_test.go
- consensus/signatureschemes/blsmultisig/hash.go
- consensus/signatureschemes/blsmultisig/hash_test.go
- consensus/signatureschemes/blsmultisig/key.go
- consensus/signatureschemes/blsmultisig/memcache.go
- consensus/signatureschemes/bridgesig/ecdsa_test.go
- incognitokey/keygenfortest/main.go
- netsync/netsync.go
- rpcserver/rpcservice/walletservice.go
- server.go
> Big Update

- .gitignore
- specs/ethereum_bridge.md
We'll be making all of our specs open-source.  The team will write specs as Markdown, commit frequently on specs changes, and welcome feedback from the community. 
Closes #299
> Open source all of our specs

- wallet/hdwallet.go
Check length of key
Closes #303
> - fix bug key error

- blockchain/blockchain.go
- rpcserver/rpcservice/walletservice.go
> - fix bug for issue #292

- .gitignore
- README.md
Update README file to explain more about the project and provide the latest instructions.
Closes #290
> [doc] New README

- .gitignore
- process/coding_style.md
- process/workflow.md
- specs/architecture.md
add 2 first processes to help the project run better
1.  incognito coding style (/process/coding_style.md)
2.  development workflow (/process/workflow.md)
@thaibao-incognito @0xmerman please expand 1 above
closes #318
> Add "/process/"

- .gitignore
- specs/architecture.md
Add a high-level architecture overview and links to key packages in the code
Closes #309
> Add architecture specs

- blockchain/beaconprocess.go
- blockchain/beaconproducer.go
- blockchain/blockchain.go
- blockchain/constants.go
- blockchain/error.go
- blockchain/params.go
- blockchain/revert.go
- blockchain/salary.go
- consensus/blsbft/validation.go
- consensus/key.go
- metadata/constants.go
- metadata/devblockreward.go
- metadata/error.go
Closes #331 
Update the name of Community fund address.
Change the formula for calculating the reward.
> Change division of reward amount:

- specs/mainnet_v0_configuration.md
Detail a list of network parameters, their initial values, and the reasons behind them.
Closes #339 #334
> Mainnet v0 configuration

- specs/transaction_fees.md
this specs details how minimum transaction fees work for both PRV and any pToken.
closes #345
> [specs] Minimum transaction fees

- consensus/engine.go
> fix issue #351

- utility/genkeywithpassword.go
create generate keyset file - new elliptic curve
> #317 testing tutorial: create function to gererate keyset

- rpcserver/constants.go
- rpcserver/http_beststate.go
- rpcserver/jsonresult/getshardbeststatedetail.go
- rpcserver/rpcinterface.go
> add rpc getShardBestStateDetail

- specs/edrwards25519.md
> Spec for new Edwards25519 Curve

- GettingStarted.md
- test-chain.go
> upload testscript and update instruction

- blockchain/beaconpdeprocess.go
- blockchain/beaconpdeproducer.go
- blockchain/constants.go
- blockchain/pdetxsbuilder.go
- blockchain/pdeutils.go
- metadata/pdetraderequest.go
- metadata/pdewithdrawalrequest.go
- metadata/pdewithdrawalresponse.go
The PR is to update the formula for DEX.
> Update exchange formula

- blockchain/beaconpdeprocess.go
- blockchain/beaconpdeproducer.go
- metadata/metadata.go
The PR is to convert all calculations on big numbers to big.Int in order to avoid uint64 overflow issue.
> Convert all calculations on big numbers to big.Int

- GettingStarted.md
#317 test file moved to incognito-chain/testexample/test-chain.go
> #317 Update GettingStarted.md

- blockchain/beaconpdeprocess.go
- blockchain/beaconpdeprocess_test.go
- blockchain/beaconpdeproducer.go
- blockchain/beaconpdeproducer_test.go
The PR is to add unit-tests for PDE.
> Write unit-tests for PDE

- config.go
- server.go
> - Update config for time life of tx in pool and scan resend tx

- specs/detail_reward_for_validator.md
Spec for the detailed reward for validator
> Spec detail reward

- rpcserver/constants.go
- rpcserver/http_tx.go
- rpcserver/jsonresult/getreceivedtransactions.go
- rpcserver/rpcinterface.go
- rpcserver/rpcservice/txservice.go
> - RPC for tx

- blockchain/beaconbridgeproducer.go
- blockchain/beaconpdeprocess.go
- blockchain/beaconpdeproducer.go
- blockchain/pdetxsbuilder.go
- blockchain/pdeutils.go
- blockchain/shardproducer.go
- common/constants.go
- database/error.go
- database/interface.go
- database/lvdb/common.go
- database/lvdb/pde.go
- metadata/common.go
- metadata/constants.go
- metadata/pdecontribution.go
- metadata/pdecontributionresponse.go
- metadata/pdetraderequest.go
- metadata/pdewithdrawalrequest.go
- rpcserver/http_pde.go
The PR is to update PDE add/remove liquidity logic.
> Update PDE add/remove liquidity logic

- blockchain/beaconbridgeproducer.go
- blockchain/beaconpdeproducer.go
The purposes of the PR are to:
- Sort trade orders by fee per value in order to allow the trading fee to be driven by the market
- Adjust trading formula a bit in order to make it more reasonable
> Sort trade orders by fee per value and adjust trading formula

- peer/constants.go
- peer/peer.go
- peer/peer_test.go
- server.go
> - update peer protocol id by version of node app

- blockchain/beaconbridgeproducer.go
- blockchain/beaconprocess.go
- blockchain/beaconproducer.go
- blockchain/beaconstatefulinsts.go
The PR is to fix race conditions pde issues.
> Fix race conditions pde issues

- wasm/gomobile/txnormal.go
- wasm/main.go
> stop auto staking tx gomobile

- rpcserver/http_wallet.go
- rpcserver/jsonresult/listcustomtokenresult.go
> - add more info into RPC

- privacy/zeroknowledge/paymentwitness.go
> fix bug tx no output, has only fee

- rpcserver/constants.go
- rpcserver/http_pde.go
- rpcserver/rpcinterface.go
The PR is to create apis for pdex analytics. (related to #498)
> APIs for pdex analytics

- blockchain/messages.go
- blockchain/synker.go
- peerv2/connmanager.go
- peerv2/utils.go
- Remove implicit code when pick a topic to publish msg to shard.
> Refactor code

- blockchain/messages.go
- blockchain/syncblockutils.go
- blockchain/synker.go
- mempool/shardtobeaconpool.go
- netsync/constants.go
- peerv2/blockprovider.go
- peerv2/blockrequester.go
- peerv2/connmanager.go
- peerv2/constants.go
- server.go
- Fix bugs cache block in get blk need to sync functions.
- Fix the way to call sync block via peerstate.
- Fix bugs no shardtobeaconpool information in peerstate beacon.
- Add functions support request blocks by specific heights.
> Fix bugs synker & peer state

- bin/bridge/eth-lightnode-monitoring.py
The PR is to create a script in order to monitor and restart automatically eth light node in case there's any problem. (Closes #393)
> ETH light node monitoring

- blockchain/params.go
- peerv2/connmanager.go
- server.go
- Allow register/pub/sub msg TxCustomTokenPrivacy
- Remove Os.Exit
- Remove checkforce for deploy devnet
> Highway hotfix

- blockchain/blockchain.go
- blockchain/synker.go
- rpcserver/ws_account.go
- server.go
- Check nil Output coin ws_account.go
- Check layer and role before publish node state (a.k.a peer state)
> Hot fix access invalid memory

- peerv2/connmanager.go
- peerv2/connmanager_test.go
- peerv2/param.go
- Calling rpc for get all of hw peer ID
- add unittest
> Remove ipfs address

- blockchain/beaconpdeproducer.go
- common/constants.go
- metadata/metadata.go
The PR is to add more conditions while adding liquidity for newly created pairs on dex.
> Pdex min liquidity for new pair

- netsync/getblock.go
- peerv2/blockprovider.go
- peerv2/blockrequester.go
- peerv2/connmanager.go
- server.go
- Add sync block shard and beacon by hash
- Add function get block with hash in netsync
> Highway getblkbyhash

- blockchain/synker.go
- mempool/shardpool.go
- Fix the way to get latest valid height in shardpool.
- Update log.
> Update logic synker

- blockchain/revert.go
> fix revert bug

- blockchain/synker.go
- Delete useless code, insert all available s2b/crossshard block into
new beacon block and dont care other node.
> Hot fix synker

- blockchain/beaconpdeprocess.go
- blockchain/beaconpdeproducer.go
- blockchain/pdetxsbuilder.go
- blockchain/shardproducer.go
- common/constants.go
- database/interface.go
- database/lvdb/pde.go
- metadata/pdecontribution.go
- metadata/pdecontributionresponse.go
- metadata/pdetraderesponse.go
- rpcserver/constants.go
- rpcserver/http_pde.go
- rpcserver/rpcinterface.go
- rpcserver/rpcservice/databaseservice.go
> Update pde adding liquidity formula

- peerv2/utils.go
> - Fix issue #635

- blockchain/messages.go
- blockchain/syncblockutils.go
- blockchain/syncblockutils_test.go
- blockchain/synker.go
- mocks/DatabaseInterface.go
- netsync/netsync.go
- Remove unuse code.
- Remove checking each of peerstate for syncblock, just call, highway will choose peer and sync.
- Sync range of missing crossshard block via beacon beststate and
database instead of sync one block per time.
- Refactor code.
related #605
> [highway] Update synker and add unittest

- blockchain/salary.go
- database/interface.go
- database/lvdb/epochreward.go
- metadata/metadata.go
- metadata/withdrawreward.go
- Let user receive custom token reward, which created by custom token
fee.
- This change let user received reward by some coinIDs, but it does not
mean user can withdraw them, cuz some coinIDs just available at some
shards.
- Withdraw this reward can be completed if someone make these coinIDs available at shards they want, like create crossshard tx (or wait for another user do it).
close #649
> Hot fix choose coin ID for reward

- blockchain/blockchain.go
- Add check token type with CrossShardToken map, current code base just
checking with mapPrivacyCustomToken
> Hot fix get token type of tokenID

- rpcserver/ws_account.go
> - Fix issue #648

- specs/portalv2.md
@duyhtq  Please review and merge the PR then we'll be able to continue working on this stuff, thanks.
> Create portal v2 spec

- server.go
- Broadcast all block from shard to beacon pool instead of latest block
only.
> Update data for publish peerstate

- peerv2/constants.go
Hot fix deadlock BlockRequester
> Highway v1 new

- blockchain/synker.go
Update Islatest lock
- Change from Mutex->RWMutex, cuz too much funcs call IsLatest() and lock them, it make UpdateState() locked => rising CPU, RAM
> Update Islatest lock

- blockchain/beaconprocess.go
- blockchain/shardcrossprocess.go
- blockchain/shardproducer.go
- blockchain/synker.go
- mempool/crossshardpool.go
This reverts commit df1dd0bb97155c1d5366973bce63b53a1bb80097.
> Revert "Add debug logs to cross shard mempool"

- common/common_test.go
- mempool/mempool_test.go
- rpcserver/rpcservice/txservice.go
- specs/burning_address.md
- transaction/common.go
- transaction/common_test.go
- transaction/error.go
- transaction/txprivacy.go
- transaction/txprivacy_test.go
- transaction/txprivacytoken.go
- transaction/txprivacytoken_test.go
- transaction/txprivacytokendata_test.go
Estimate Size before Init Tx. 
Reject if estimateTxSize > common.MaxTxSize.
> Limited input

- specs/portal.md
@thach-incognito - please help review the spec, thanks.
> Update portal spec

- rpcserver/rpcservice/txservice.go
- transaction/txprivacytokendata.go
> - validate data

- blockchain/blockchain.go
- blockchain/constants.go
- blockchain/shardprocess.go
- blockchain/shardproducer.go
- metadata/metadata.go
- privacy/zeroknowledge/aggregaterange/aggregaterange.go
- privacy/zeroknowledge/aggregaterange/aggregaterange_test.go
- privacy/zeroknowledge/aggregaterange/innerproductargument.go
- privacy/zeroknowledge/payment.go
- rpcserver/jsonresult/listcustomtokenbalanceresult.go
- rpcserver/rpcservice/txservice.go
- transaction/batchtransaction.go
- transaction/common.go
- transaction/common_test.go
- transaction/error.go
- transaction/txprivacy.go
- transaction/txprivacy_test.go
- transaction/txprivacytoken.go
Add batch verification for inner product
> Bulletproof batch verification

- metadata/issuingethrequest.go
- metadata/issuingrequest.go
> - fix issue #790

- metadata/constants.go
- metadata/issuingethrequest.go
@thaibao-incognito please help review the PR, thanks.
> Fix potential issues of eth-bridge

- blockchain/beaconprocess.go
- blockchain/shardprocess.go
- blockchain/shardproducer.go
- mempool/crossshardpool.go
Get shard committee from  beacon height (confirming crossShard) - 1
Marshal beacon beststate after modify LastCrossShardState
> Fix crossshard committee validation and store LastCrossShardState

- blockchain/beaconportalliquidationprocess.go
- blockchain/beaconportalprocess.go
- blockchain/portalutils.go
> Fix bug converting exchange rates

- blockchain/portalutils.go
- common/constants.go
- metadata/portalportingrequest.go
- metadata/portalredeemliquidateexchangerates.go
- metadata/portalredeemrequest.go
1. Fix bug copy array in pick single custodian func
2. Set minimum amount for portal tokens
> Fix bugs portal

- blockchain/beaconportalliquidationprocess.go
- blockchain/beaconportalliquidationproducer.go
- blockchain/beaconportalprocess.go
- blockchain/beaconportalproducer.go
- blockchain/beaconportalrewardprocess.go
- blockchain/beaconprocess.go
- blockchain/beaconproducer.go
- blockchain/beaconstatefulinsts.go
- blockchain/blockchain.go
- blockchain/params.go
- blockchain/portalutils.go
- blockchain/salary.go
- common/constants.go
- dataaccessobject/statedb/stateobject_portal_reward.go
- rpcserver/http_portalexchangerates.go
- rpcserver/http_portalliquidatetpexchangerates.go
- rpcserver/rpcservice/portalservice.go
- Create portal params in blockchain
- Set minimum rewards for custodians
- Fix bugs calculating minimum amount for topup
> Create portal params in blockchain

- rpcserver/http_beststate.go
- rpcserver/rpcservice/error.go
***Change:***
- Remove panic() action in json rpc of `getbeaconbeststate`
- Change way of getting block from many views in `getbeaconbeststate` json rpc
> [optimize-beststate] Remove panic of json rpc get beacon beststate

- blockchain/shardprocess.go
- blockchain/shardproducer.go
**Change:**
- Move newCommitteeChange() out param function
- Use temporary variable instead
> [committee-change] Update committechange in shard process

- blockchain/blockchain.go
- blockchain/restoreBeststate.go
- metrics/monitor/monitor.go
- syncker/shardsyncprocess.go
- syncker/utils.go
- init active shards so that we can generate correct shard committee
> Fix restore beacon view from blockhash

- syncker/beaconsyncprocess.go
- syncker/shardsyncprocess.go
-> make sure rpc return final info
> fullnode delay 1 block 

- blockchain/constants.go
- rpcserver/http_wallet.go
- syncker/beaconsyncprocess.go
- syncker/shardsyncprocess.go
- Update new smartcontract
- Fix syncker loop
- Change RPC logic
> Fix errors

- blockchain/shardprocess.go
- blockchain/shardproducer.go
- syncker/syncker.go
- Add more log
- Fix request pointer when get crossX
- Fix request with limit
> Fix get crossX

- common/constants.go
- go.mod
- peerv2/connmanager.go
Reverts incognitochain/incognito-chain#1033
> Revert "Dev/master consensus v2 optimized upgradelibp2p"

- consensus/signatureschemes/blsmultisig/bls_test.go
- consensus/signatureschemes/blsmultisig/key.go
> Remove cache in bls validate and update testcase

- utility/genkeylistjson/genkeypairprivacy_AIO.go
generate keylist.json with privatekey in it, for testing purpose
> add genkeypairprivacy_AIO

- blockchain/returnstaking.go
- dataaccessobject/statedb/accessor_consensus.go
- Add check candidate in current epoch candidate
> Update check candidate if it is out chain

- blockchain/bridgetxsbuilder.go
- metadata/contractingrequest.go
Reverts incognitochain/incognito-chain#1094
> Revert "Improve shielding processes"

- consensus_v2/blsbftv2/bftactorv2.go
- Only Vote if propose block still in current time slot
> Improve vote condition

- consensus_v2/blsbftv2/bftactorv2.go
- syncker/beaconsyncprocess.go
- syncker/shardsyncprocess.go
- Delay next validation when validating error
- Fix stream block return nil channel
> Fix stream block

- blockchain/beaconpdeproducer.go
- blockchain/pdeutils.go
The PR is to improve pDEX process that only creates refund transactions if amount > 0.
> Does not refund trade fee if amount is equal to 0

- consensus_v2/blsbftv2/bftactorv2.go
Proposer will not vote, until it receives at least 1 vote
The valid block to vote, need to be the next height
> Optimize BFT Flow

- blockchain/interface.go
- consensus_v2/engine.go
- metrics/monitor/monitor.go
- rpcserver/constants.go
- rpcserver/http_poolinfo.go
- rpcserver/jsonresult/getmininginforesult.go
- rpcserver/jsonresult/poolinfo.go
- rpcserver/rpcinterface.go
- rpcserver/rpcserver.go
- rpcserver/rpcservice/synkerservice.go
- syncker/beaconsyncprocess.go
- syncker/shardsyncprocess.go
- syncker/syncker.go
- Add SyncStat RPC
- Update monitor flow
> New monitor flow

- blockchain/beaconprocess.go
Cache beacon view for fast retrieval
> Optimize producing block process

- blockchain/beaconchain.go
- blockchain/blockchain.go
- blockchain/shardprocess.go
- blockchain/shardproducer.go
- consensus_v2/blsbftv2/bftactorv2.go
- consensus_v2/blsbftv3/bftactorv3.go
- consensus_v2/engine.go
Fix upgrade version for blsbft
> Fix upgrade version for blsbft

- consensus_v2/blsbftv3/bftactorv3.go
- consensus_v2/engine.go
Fix bug in get list keys for blsbft consensus
> Fix bug in get list keys for blsbft consensus

- blockchain/params.go
[dcs] fix initialIncognito value
> [dcs] fix initialIncognito value

- blockchain/beaconchain.go
- blockchain/shardchain.go
- blockchain/types/shardblock.go
- consensus_v2/blsbftv3/bftactorv3.go
- consensus_v2/key.go
- multiview/multiview.go
> [dcs] add version 3 to block

- blockchain/beaconbeststate.go
- blockchain/beaconprocess.go
- blockchain/committeestate/beacon_committee_state_v1.go
- blockchain/committeestate/beacon_env.go
- blockchain/constants.go
- blockchain/shardprocess.go
- blockchain/shardproducer.go
Hotfix - Stop and Swap Instructions in 1 block
**move update beacon committee state after swap instructions inside the instructions loop**
> Hotfix - Stop and Swap Instructions in 1 block

- mempool/mempool.go
- rpcserver/constants.go
- rpcserver/http_txpool.go
- rpcserver/jsonresult/getmempoolresult.go
- rpcserver/rpcinterface.go
- rpcserver/rpcservice/txservice.go
The PR is to:
- Remove GetMempoolInfoDetails rpc
- Include TpKeys (tx mempool keys) to GetMempoolInfo rpc's result
> Update GetMempoolInfo rpc to including tpKey in its result

- blockchain/beaconprocess.go
- blockchain/error.go
• Recheck previous pde state and DB
• Clear DeletedWaitingPDEContributions for new pdeState
> Check pde state before sign block

- rpcserver/jsonresult/getblockresult.go
[config] add proposer time to block json result
> [config] add proposer time to block json result

- metadata/issuingevmrequest.go
- metadata/issuingevmresponse.go
Update jsontag to make the updated evm bridges compatible with the old eth shielding, unshielding txs
> ETH bridge compatibility

- rpcserver/http_txpool.go
- rpcserver/rpcservice/txservice.go
Fix rpc:
- DecryptOutputCoin
- MempoolEntry
> Product updaterpc

- blockchain/accessor_blockchain.go
- blockchain/shardproducer.go
- Fix when limit shard blocks for beacon producer
- Fix when limit beacon blocks for shard producer
> Fix overflow which lead to wrong number of  get block

- blockchain/pdex/interface.go
- blockchain/pdex/state_base.go
- blockchain/pdex/state_v2.go
- blockchain/pdex/utils.go
- blockchain/shardproducer.go
- config/local/param.yaml
- config/mainnet/param.yaml
- config/param.go
- config/testnet-1/param.yaml
- config/testnet-2/param.yaml
- rpcserver/constants.go
- rpcserver/http_pdexv3.go
- rpcserver/jsonresult/pdexv3.go
- rpcserver/rpcinterface.go
- rpcserver/rpcservice/error.go
- Add interface for RPC getting pDEX state
- Refactor params.yaml for pdex params
> Dev/pdex v3/state

- transaction/tx_ver2/tx_token_ver2.go
- Added code for checking the burning tokenId is valid
> Add tokenId validation code when burning

- blockchain/pdex/tx_builder_v1.go
- blockchain/pdex/tx_builder_v2.go
- blockchain/shardbeststate.go
- blockchain/shardproducer.go
> Refactor pDex tx builder

- metadata/issuingevmrequest.go
=> handle more tx types from ethereum
> update shield flow 

- blockchain/blockchain.go
- config/testnet-2/param.yaml
- When restoring beacon view, if NumberOfShardBlock is nil, then initiate it
- Fix param of assign v3 height
> Initiate NumberOfShardBlock 

- rpcserver/http_pdexv3.go
- rpcserver/utils.go
Fix params of withdraw liquidity rpc
> [hotfix] share amount of withdraw liquidity rpc layer

- blockchain/pdex/state_processor_v2.go
- blockchain/pdex/state_producer_v2.go
- metadata/pdexv3/add_order.go
- metadata/pdexv3/withdraw_order.go
- rpcserver/http_pdexv3.go
includes an RPC format change (withdrawOrder) & status query change (add tokenID)
> Pdexv3: WithdrawOrder for both tokens

- rpcserver/http_pdexv3.go
Update json result status remove marshal format
> [pdex] Update json result status remove marshal format

- blockchain/pdex/state_processor_v2.go
- blockchain/pdex/state_processor_v2_test.go
- dataaccessobject/rawdbv2/accessor_pdexv3.go
hotfix waiting contribution verify wrong condition
> [pdex] hotfix waiting contribution verify wrong condition

- blockchain/pdex/pool_pair_state.go
- blockchain/pdex/staking_pool_state.go
- blockchain/pdex/state_producer_v2.go
- blockchain/pdex/state_v2.go
- blockchain/pdex/state_v2_test.go
Fix empty state change when not change state in mem
> [pdex] Fix empty state change when not change state in mem

- blockchain/pdex/state_producer_v2.go
- Sort key before build instructions
> Fix order of distributing PDEX and staking reward instructions

- blockchain/pdex/pool_pair_state.go
- blockchain/pdex/state_processor_v2.go
- blockchain/pdex/state_processor_v2_test.go
- blockchain/pdex/state_producer_v2.go
- blockchain/pdex/tx_builder_v2.go
- blockchain/pdex/v2utils/reserve.go
- blockchain/pdex/v2utils/utils.go
- config/config.go
Fix not get diff for lpfee per shares in pool pair
> [pdex] Fix not get diff for lpfee per shares in pool pair

- blockchain/pdex/order_book.go
- blockchain/pdex/pool_pair_state.go
- blockchain/pdex/state_v2.go
- blockchain/pdex/state_v2_test.go
- blockchain/pdex/v2utils/state_change.go
- rpcserver/http_pdexv3.go
- Move Order from StateChange to PoolPairChnge
> Move order changes into pool pair

- config/testnet-1/param.yaml
Update assign v3 checkpoint height
> [pdex] Update assign v3 checkpoint height

- Makefile
- blockchain/pdex/params.go
- blockchain/pdex/pool_pair_state.go
- blockchain/pdex/state_producer_v2.go
- blockchain/pdex/state_v2.go
1. Fix bug in modify param 
2. Fix bug in Calculate liquidity add to pool
3. Change orders of instructions
> [pdex] Fix bug in modify param + calculate liquidity add to pool

- blockchain/pdex/state_producer_v2.go
Add more conditions for handling error tx from shard in beacon side
> [pdex] Update more conditions for handling error tx

- blockchain/committeestate/consensus_swap_rule_v2.go
Assign Offset is 1 when it match condition
> Calculate Assign Offset V2

- blockchain/accessor_transaction.go
- blockchain/beaconbeststate.go
- blockchain/shardprocess.go
- metadata/relayingheader.go
- metadata/withdrawrewardresponse.go
- syncker/utils.go
- Enable verifying tx when signing
- Verify Withdraw response
- Verify relay header
- Modify insert batch flow (validate block whenever change in committee root hash)
- Fix access nil pointer from GetMissingSignnature
> Fix Issues

- metadata/portalredeemrequest.go
- Fixed bug checking redeem fee of a portal v3 redeem request
> [hotfix] fix bug sync portal v3

- blockchain/pdex/pool_pair_state.go
- blockchain/pdex/pool_pair_state_test.go
Fix calculate virtual amount with out range uint64 - add liqudity
> [pdex] Fix calculate virtual amount with out range uint64 - add liqudity

- blockchain/pdex/pool_pair_state.go
- blockchain/pdex/state_producer_v2.go
- blockchain/pdex/state_v2_utils.go
- blockchain/pdex/utils.go
- instruction/pdexv3/accept_unstaking.go
- instruction/pdexv3/accept_withdraw_liquidity.go
- instruction/pdexv3/mint_nft.go
- instruction/pdexv3/reject_staking.go
- metadata/pdexv3/withdraw_liquidity_response.go
Ensure not out of range with case uint64()
> [pdex] Ensure not out of range with case uint64()

- blockchain/blockchain.go
- blockchain/pdex/state_v1.go
- blockchain/restorebeststate.go
- blockchain/shardchain.go
- blockchain/shardprocess.go
- blockchain/shardproducer.go
- config/testnet-2/param.yaml
- mempool/mempool.go
- rpcserver/http_beststate.go
- rpcserver/rpcservice/txservice.go
- rpcserver/ws_beststate.go
Add get beacon view for verify transaction (verify by beacon view in tx)
> Add get beacon view for verify transaction (verify by beacon view in tx)

- blockchain/beaconprocess.go
- blockchain/blockchain.go
- blockchain/pdex/statedb.go
- blockchain/restorebeststate.go
- blockchain/shardchain.go
- blockchain/shardprocess.go
- config/mainnet/param.yaml
- mempool/mempool.go
- metadata/common/metadata.go
- metadata/exports.go
- rpcserver/rpcservice/txservice.go
- rpcserver/ws_beststate.go
optimize get pde state with cache
> optimize get pde state with cache

- common/constants.go
- Increase tx size limit to 500 KBs
> Increase Tx Size Limit to 500KBs

- blockchain/blockchain.go
- syncker/syncker.go
- Only init view when there is no bestview store in DB
- Allow sync shard immediately, if the shard is specified in relayshards param
> fix init view

- Makefile
- blockchain/pdex/state_producer_v2.go
- blockchain/pdex/state_producer_v2_test.go
- blockchain/pdex/trade_test.go
- blockchain/pdex/tx_builder_v2.go
- blockchain/pdex/v2utils/withdraw_liquidity.go
- blockchain/shardproducer.go
- metadata/pdexv3/unstaking_request.go
- metadata/pdexv3/withdraw_liquidity_request.go
- metadata/pdexv3/withdraw_liquidity_response.go
try to fix handle null ota receivers
> [pdex] try to fix handle null ota receivers

- blockchain/accessor_transaction.go
- Remove unnecessary decrypting log
> [hot-fix] remove unnecessary log

- rpcserver/constants.go
- rpcserver/http_wallet.go
- rpcserver/rpcinterface.go
- Add new RPC: `listprivacycustomtokenids`
> Add listprivacycustomtokenids

- blockchain/beaconprocess.go
- blockchain/interface.go
- blockchain/shardprocess.go
add current block to pool if need to sync prev block
> Fix missing fork block in pool

- consensus_v2/blsbft/actor_v2_byzantine_detector_test.go
- dataaccessobject/rawdb_consensus/db.go
[Hotfix] change IntToBytes to Int32ToBytes
> [Hotfix] change IntToBytes to Int32ToBytes

- blockchain/beaconchain.go
- blockchain/shardchain.go
- blockchain/shardproducer.go
- consensus_v2/blsbft/actor_v2.go
- consensus_v2/blsbft/actor_v2_byzantine_detector.go
- consensus_v2/blsbft/actor_v2_byzantine_detector_test.go
- consensus_v2/blsbft/actor_v2_rule_propose.go
- consensus_v2/blsbft/actor_v2_rule_propose_test.go
- Copy committee to signing committee
- If previous block propose info failed to produce sigs then by pass
> Hotfix for lemma 2 test on testnet 1

- blockchain/pdex/statedb.go
- rpcserver/rpcservice/pdexv3service.go
[pdex] remove nftIDs in get all pdexv3 state
> [pdex] remove nftIDs in get all pdexv3 state

- consensus_v2/blsbft/actor_v2.go
> Hotfix checking height for bft rule

- consensus_v2/blsbft/actor_v2.go
Node receive vote for a block before the propose-msg will also process lemma 2 rule the propose-msg and keep the vote information
> Consensus fix receive block after vote

- blockchain/beaconbeststate.go
- blockchain/pdex/interface.go
- blockchain/pdex/state_base.go
- blockchain/pdex/state_v2.go
- metadata/common/metadata.go
- metadata/common/mocks/BeaconViewRetriever.go
- metadata/pdexv3/unstaking_request.go
- metadata/pdexv3/withdraw_liquidity_request.go
- metadata/pdexv3/withdraw_lp_fee_request.go
- metadata/pdexv3/withdraw_order.go
- metadata/pdexv3/withdraw_staking_reward_request.go
- rpcserver/http_pdexv3.go
- rpcserver/rpcservice/outputcoinservice.go
Add verify for metadata if user burn wrong accessOTA with accessID
> [pdex] Add verify process for burnt wrong accessOTA

- blockchain/pdex/state_producer_v2.go
- blockchain/pdex/state_producer_v2_utils.go
- blockchain/pdex/tx_builder_v2.go
- blockchain/pdex/v2utils/add_liquidity.go
- dataaccessobject/rawdbv2/accessor_pdexv3.go
- metadata/pdexv3/add_liquidity_request.go
- metadata/pdexv3/add_liquidity_response.go
- metadata/pdexv3/add_order.go
- metadata/pdexv3/staking_request.go
- metadata/pdexv3/unstaking_request.go
- metadata/pdexv3/utils.go
- metadata/pdexv3/utils_test.go
- metadata/pdexv3/withdraw_liquidity_request.go
- metadata/pdexv3/withdraw_lp_fee_request.go
- metadata/pdexv3/withdraw_order.go
- metadata/pdexv3/withdraw_staking_reward_request.go
- rpcserver/http_pdexv3.go
[pdex] Fix choose OtaReceiver by OtaReceiver field
> [pdex] Fix choose OtaReceiver by OtaReceiver field

- blockchain/blockchain.go
- mempool/mempool.go
Init feature stat after init chain state
> Fix bug init feature stat

- consensus_v2/blsbft/actor_v2.go
- consensus_v2/blsbft/actor_v2_rule_propose.go
- consensus_v2/blsbft/actor_v2_rule_vote.go
- consensus_v2/blsbft/block_info.go
- consensus_v2/blsbft/validation.go
- dataaccessobject/rawdb_consensus/consensus_actorv2.go
- dataaccessobject/rawdb_consensus/db.go
- rpcserver/http_testing.go
- Remove receive block by height
- Store vote when receiving vote
> Improve BFT

- config/testnet-2/param.yaml
[pdex] Add auto enable feature flag
> [pdex] Add auto enable feature flag

- config/testnet-2/param.yaml
Reverts incognitochain/incognito-chain#1432
> Revert "[pdex] Add auto enable feature flag"

- consensus_v2/blsbft/actor_v2.go
- consensus_v2/blsbft/actor_v2_rule_propose.go
- consensus_v2/blsbft/actor_v2_rule_vote.go
- consensus_v2/blsbft/block_info.go
- consensus_v2/blsbft/validation.go
- dataaccessobject/rawdb_consensus/consensus_actorv2.go
- dataaccessobject/rawdb_consensus/db.go
- rpcserver/http_testing.go
Reverts incognitochain/incognito-chain#1430
> Revert "Improve BFT"

- blockchain/blockchain.go
- mempool/mempool.go
Reverts incognitochain/incognito-chain#1426
> Revert "Fix bug init feature stat"

- blockchain/pdex/state_producer_v2.go
- blockchain/pdex/utils.go
Add Sort auto withdraw orders for poolPairs map
> [hotfix-pdex] Sort auto withdraw orders

- blockchain/pdex/state_producer_v2.go
Hotfix sort withdraw order results
> [pdex] Hotfix sort withdraw order results

- rpcserver/rpcservice/constants.go
- rpcserver/rpcservice/pdexv3service.go
Add option get nftIDs on mem by rpc get state
> [pdex] Add option get nftIDs on mem by rpc get state

- pruner/pruner_manager.go
> [state-prune] Fix get prune report error

- bin/inc_pnode_installer.sh
create a separate installer file for pnode
> Pnode installer

- config/testnet-2/param.yaml
- Update contract address for fantom and ethereum.
> Update contract addresses

- blockchain/bridgeagg/state_processor.go
- blockchain/bridgeagg/state_producer.go
- portal/params.go
- Increase default unshielding fee for portal v4
- Increase number of blocks for batching
- Fix bug typo in punified
> Update portal v4 params

- blockchain/blockgenerator.go
- blockchain/shardchain.go
- blockchain/shardprocess.go
- blockchain/shardproducer.go
- consensus_v2/blsbft/actor_v2.go
- consensus_v2/blsbft/actor_v3_propose.go
- testsuite/remoteRPCClient.go
> Fix timming & get pending tx

- blockchain/beaconbeststate.go
- blockchain/committeestate/beacon_committee_state_v3.go
- blockchain/committeestate/environment.go
- config/constants.go
- config/mainnet/param.yaml
- config/testnet-2/param.yaml
- Slash Validator  will go to sync pool, instead of returning stake amount
> Slash to Syncpool
